apiVersion: v1
kind: Secret
metadata:
  name: postgrest-db
type: Opaque
stringData:
  PGRST_DB_URI: "postgresql://app:CgBzIMf6XX7o2PNSfjUYkiyX3llE9DSIYuHmDxdxfJo0ZQ3ysTy8TC8a8qTdyyDs@cluster-user-a-rw.edb-emea-user-a:5432/app"
  PGRST_DB_SCHEMA: "public"
  PGRST_DB_ANON_ROLE: "app"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      containers:
      - name: postgrest
        image: postgrest/postgrest:v14.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: postgrest-db
        env:
        - name: PGRST_SERVER_CORS_ALLOWED_ORIGINS
          value: "http://swagger-ui-edb-emea-user-a.apps-crc.testing"
        - name: PGRST_OPENAPI_MODE
          value: "follow-privileges"
        - name: PGRST_OPENAPI_SERVER_PROXY_URI
          value: "http://postgrest-edb-emea-user-a.apps-crc.testing"
---
apiVersion: v1
kind: Service
metadata:
  name: postgrest
spec:
  selector:
    app: postgrest
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: postgrest
spec:
  to:
    kind: Service
    name: postgrest
  port:
    targetPort: http
