apiVersion: v1
kind: Secret
metadata:
  name: postgrest-secret
type: Opaque
stringData:
  PGRST_DB_URI: "postgresql://app:oT9nfL4gMVPIjYUZa3kYr9P6YgVPIJR6NHhFnPdN7vqP9gSok4JrQCHiFelWCy2M@cluster-user-b-rw.edb-emea-user-b:5432/app"
