apiVersion: v1
kind: ConfigMap
metadata:
  name: postgrest-config
data:
  PGRST_DB_SCHEMA: "public"

  PGRST_DB_ANON_ROLE: "app"

  PGRST_SERVER_CORS_ALLOWED_ORIGINS: "http://localhost:5173,http://localhost:8080,https://worldcup-ui-edb-emea-user-b.apps-crc.testing,https://swagger-ui-edb-emea-user-b.apps-crc.testing"

  PGRST_OPENAPI_SERVER_PROXY_URI: "https://postgrest-edb-emea-user-b.apps-crc.testing"
