INSERT INTO teams (code, name, confederation, rating) VALUES
('FRA','France','UEFA',92),
('BRA','Brazil','CONMEBOL',91),
('ARG','Argentina','CONMEBOL',90),
('ENG','England','UEFA',90),
('ESP','Spain','UEFA',89),
('GER','Germany','UEFA',88),
('POR','Portugal','UEFA',88),
('NED','Netherlands','UEFA',87),
('ITA','Italy','UEFA',86),
('BEL','Belgium','UEFA',85),
('CRO','Croatia','UEFA',84),
('URU','Uruguay','CONMEBOL',84),
('COL','Colombia','CONMEBOL',83),
('MEX','Mexico','CONCACAF',82),
('USA','United States','CONCACAF',82),
('MAR','Morocco','CAF',82),
('JPN','Japan','AFC',81),
('SEN','Senegal','CAF',81),
('SUI','Switzerland','UEFA',81),
('DEN','Denmark','UEFA',81),
('AUT','Austria','UEFA',80),
('KOR','South Korea','AFC',80),
('ECU','Ecuador','CONMEBOL',80),
('SRB','Serbia','UEFA',79),
('POL','Poland','UEFA',79),
('SWE','Sweden','UEFA',79),
('NOR','Norway','UEFA',79),
('TUR','Türkiye','UEFA',79),
('CAN','Canada','CONCACAF',78),
('AUS','Australia','AFC',78),
('EGY','Egypt','CAF',78),
('NGA','Nigeria','CAF',78),
('ALG','Algeria','CAF',77),
('CMR','Cameroon','CAF',77),
('GHA','Ghana','CAF',76),
('CIV','Côte d''Ivoire','CAF',76),
('QAT','Qatar','AFC',75),
('IRN','Iran','AFC',75),
('KSA','Saudi Arabia','AFC',74),
('PAR','Paraguay','CONMEBOL',74),
('CHI','Chile','CONMEBOL',74),
('PER','Peru','CONMEBOL',73),
('PAN','Panama','CONCACAF',72),
('CRC','Costa Rica','CONCACAF',72),
('NZL','New Zealand','OFC',71),
('JAM','Jamaica','CONCACAF',71),
('MLI','Mali','CAF',71),
('TUN','Tunisia','CAF',71)
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    confederation = EXCLUDED.confederation,
    rating = EXCLUDED.rating;
