ALTER TABLE players
ADD COLUMN IF NOT EXISTS age INT,
ADD COLUMN IF NOT EXISTS club TEXT,
ADD COLUMN IF NOT EXISTS attack_rating INT DEFAULT 50,
ADD COLUMN IF NOT EXISTS defense_rating INT DEFAULT 50;
